### ISSUE TITLE
Some documentation in case you don't have them

### ISSUE THREAD

**Issue by GMMan** [SamuelWAnderson45/sleigh-unsp#1]
The µ'nSP Programmer's Guide (ISA documentation), µ'nSP Instruction Set Summary (extracted tables of instruction encoding), and µ'nSP Programming Tools User’s Manual (mostly compiler stuff, but explains things like calling conventions) are all available inside the µ'nSP IDE (downloadable [here](https://www.generalplus.com/1LVlangLNb1SVs6SNservice_n_support_d)). It should help with explaining the differences between the versions and provide details on how the operations work.

**Comment by SamuelWAnderson45** [comment]
Thanks. Is that new to the 4.0.0 version? I've been using the 3.0.16 version in the past and I only remember seeing the Programming Tools User’s Manual.

**Comment by GMMan** [comment]
I've not downloaded the previous version, so not sure if it was present before.
